microvmRegion: us-east-1
vertexAiProject: notebook-ml-475807
vertexAiLocation: us-central1
vertexCredentialsFile: .keys/gcp-sp.json
azureOpenAiConfigFile: .keys/azure-openai.json
publicMicrovm: true
useCodebuildEcrBaseImage: false
