model_list:
  - model_name: nova-2-lite
    litellm_params:
      model: bedrock/global.amazon.nova-2-lite-v1:0
      aws_region_name: "us-east-1"

  - model_name: minimax-m2.5
    litellm_params:
      model: bedrock/minimax.minimax-m2.5
      aws_region_name: "us-east-1"      

  - model_name: kimi-k2.5
    litellm_params:
      model: bedrock/moonshotai.kimi-k2.5
      aws_region_name: "us-east-1"      